C MAKE A FUNCTION FOR CALCULATE FACTORIAL,
C APPLY IT TO 1..10 AND WRITE RESULT
      PROGRAM FACTORIAL
      DOUBLE PRECISION D
   10 FORMAT(7H NUMBER, 2X, 9HFACTORIAL)
   20 FORMAT(I6, 2H!=, D24.16)
      DO 30 I = 1, 20
      D = FACT(I)
      WRITE(3, 20) I, D
   30 CONTINUE      
      STOP
      END

      DOUBLE PRECISION FUNCTION FACT(K)
      DOUBLE PRECISION F
      F = 1.0D0
      IF (K .EQ. 1) GOTO 110
      DO 100 L = 2, K 
      F = F * L
  100 CONTINUE
  110 FACT = F
      RETURN
      END

