C WRITE MESSAGE TO CONSOLE

      PROGRAM HELLO
      INTEGER DOUT
C I/0 DEVICES
      DATA DOUT /3/
C     DATA DOUT /6/
      WRITE(DOUT, 10)
      WRITE(DOUT, 10), 1
      STOP
   10 FORMAT(14H HELLO FORTRAN, i3)
      END
