C WRITE MESSAGE TO CONSOLE

      PROGRAM HELLO
      INTEGER DOUT
C I/0 DEVICES
      DATA DOUT /3/
c     DATA DOUT /6/
      WRITE(DOUT, 10)
      STOP
   10 FORMAT(14H HELLO FORTRAN)
      END
