C READ NUMBERS FROM UNFORMATTED FILE

      PROGRAM READRNUMS
      IMPLICIT NONE
      INTEGER DOUT, RF
      INTEGER I
      REAL RNUMS(10)
C I/0 DEVICES
      DATA DOUT /3/
C     DATA DOUT /6/
      RF = 5
      OPEN(RF, FILE = 'NUMBERS.DAT', STATUS = 'OLD',
     1 FORM = 'UNFORMATTED')
      READ(RF) (RNUMS(I), I = 1, 10)
      CLOSE(RF)
      DO 10 I = 1, 10
      WRITE(DOUT, 99) RNUMS(I)
   10 CONTINUE
      STOP
   99 FORMAT(F8.2)
      END
