C WRITE SPLITTER TO CONSOLE

      SUBROUTINE SPLIT(LENGTH)
      INTEGER DIN, DOUT, LENGTH
      COMMON /GLBLUN/DIN, DOUT
      INTEGER LINE(80)
      INTEGER I
      DATA LINE /80*1H-/
      WRITE(DOUT, 199) (LINE(I), I = 1, LENGTH)
      RETURN      
  199 FORMAT(1X, 80A1)
      END
