C WRITE SQUARE OF NUMBERS 1..10

      PROGRAM SQUARE10
      INTEGER DOUT
C I/0 DEVICES
      DATA DOUT /3/
C     DATA DOUT /6/
   10 FORMAT(7H NUMBER, 1X, 6HSQUARE)
   20 FORMAT(I6, 1X, I6)
      WRITE(DOUT, 10)
      DO 30 I = 1, 10
      J = I ** 2
      WRITE(DOUT, 20) I, J
   30 CONTINUE
      STOP
      END
