C WRITE NUMBERS TO UNFORMATTED FILE

      PROGRAM WRUNFORM
      IMPLICIT NONE
      INTEGER DOUT, RF
      INTEGER I
      REAL RNUMS(10)
C I/0 DEVICES
      DATA DOUT /3/
C     DATA DOUT /6/
      DATA RNUMS /7.0, 2.0, 10.0, 4.0, 1.0, 9.0, 3.0, 6.0, 8.0, 5.0/
      RF = 5
      OPEN(RF, FILE = 'NUMBERS.DAT', STATUS = 'UNKNOWN',
     1 FORM = 'UNFORMATTED', ERR = 10)
      WRITE(RF) (RNUMS(I), I = 1, 10)
      CLOSE(RF)
      GOTO 20
   10 WRITE(DOUT, 99)
   20 CONTINUE
      STOP
   99 FORMAT(13H WRITE ERROR!)
      END
